CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL COMMENT 'User name',
  email VARCHAR(255) NOT NULL COMMENT 'User email',
  stripe_customer_id VARCHAR(255) COMMENT 'Stripe customer ID',
  role ENUM('Free', 'Premium') NOT NULL DEFAULT 'Free' COMMENT 'User role',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);