CREATE TABLE packages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL COMMENT 'Package name',
  description TEXT NOT NULL COMMENT 'Package description',
  price DECIMAL(10, 2) NOT NULL COMMENT 'Price in USD',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- Path: tools/schema.sql
CREATE TABLE orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  package_id BIGINT UNSIGNED NOT NULL COMMENT 'Package ID',
  user_id BIGINT UNSIGNED NOT NULL COMMENT 'User ID',
  status ENUM('PENDING', 'COMPLETED', 'CANCELLED', 'FAILED') NOT NULL COMMENT 'Order status',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (package_id) REFERENCES packages(id),
  FOREIGN KEY (user_id) REFERENCES users(id) -- Assuming there is a users table
);